import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {Footer} from "@/components/footer";
import {Header} from "@/components/header";
import {MainNav} from "@/components/main-nav";
import {siteConfig} from "@/app/config/site";
import Link from "next/link";
import {ThemeProvider} from "@/components/theme-provider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <div className="flex min-h-screen flex-col">
                <Header>
                    <MainNav items={siteConfig.mainNav}/>
                    <nav className="hidden md:block">
                        <Link href="/login">
                            Login
                        </Link>
                    </nav>
                </Header>
                {children}
                <Footer>
                    <div className="container mx-auto ">
                        <div className="grid grid-cols-2 gap-8 px-4 py-6 lg:py-8 md:grid-cols-4">
                            <div></div>
                        </div>
                    </div>
                </Footer>
            </div>
        </ThemeProvider>
        </body>
        </html>
    );
}
